app:
  name: LONGPLAN
  domain: 10.10.182.135
  port: 8080
  secret: TEST

database:
  host: 10.10.182.135
  port: 5432
  name: longplan-dev
  user: longplan-team
  pass: longplan@test!1234

cmu_oauth:
  cmu_oauth_info: https://misapi.cmu.ac.th/cmuitaccount/v1/api/cmuitaccount/basicinfo
  cmu_oauth_token: https://oauth.cmu.ac.th/v1/GetToken.aspx
  cmu_oauth_redirect_url: http://10.10.182.135:8080/cmuOAuthCallback
  cmu_oauth_client_id: QYceDwquheP0VKSP2MDKJggdNZWveQjkqmDUmep8
  cmu_oauth_client_secret: sxe01uj67ad1SFyGR9CQK4pD5CMHf7CYyFunctpt
