package service

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/Long-Plan/longplan-api/internal/core/domain"
	"github.com/Long-Plan/longplan-api/internal/core/model"
	"github.com/Long-Plan/longplan-api/internal/core/port"
	"github.com/PuerkitoBio/goquery"
)

type courseDetailService struct {
	courseDetailRepo port.SysCourseDetailRepo
}

func NewCourseDetailService(courseDetailRepo port.SysCourseDetailRepo) domain.CourseDetailService {
	return &courseDetailService{
		courseDetailRepo: courseDetailRepo,
	}
}

func stringPtr(s string) *string {
	if s == "" {
		return nil // Return nil if the string is empty
	}
	return &s
}

func scrapeCourseDetail(courseNo string) (*model.SysCourseDetail, error) {
	// Fetch the HTML page
	url := fmt.Sprintf("https://mis.cmu.ac.th/tqf/coursepublic.aspx?courseno=%v&semester=2&year=2567", courseNo)
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch course details: %v", err)
	}
	defer resp.Body.Close()

	// Parse the HTML
	doc, err := goquery.NewDocumentFromReader(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to parse HTML: %v", err)
	}

	// Initialize the course detail object
	var courseDetail model.SysCourseDetail

	// Scrape course number
	courseDetail.CourseNo = strings.TrimSpace(doc.Find("#lblCourseID").Text())

	// Scrape course title (English and Thai)
	courseDetail.TitleLongEN = strings.TrimSpace(doc.Find("#lblCourseTitleEng").Text())
	courseDetail.TitleLongTH = strings.TrimSpace(doc.Find("#lblCourseTitleTha").Text())

	// Scrape course description (English and Thai)
	courseDetail.CourseDescEN = stringPtr(strings.TrimSpace(doc.Find("#lblCourseDescriptionEng").Text()))
	courseDetail.CourseDescTH = stringPtr(strings.TrimSpace(doc.Find("#lblCourseDescriptionTha").Text()))

	// Scrape course credit
	creditText := strings.TrimSpace(doc.Find("#lblCredit").Text())
	creditParts := strings.Split(creditText, "(")
	if len(creditParts) > 0 {
		courseDetail.Credit, _ = strconv.Atoi(strings.TrimSpace(creditParts[0]))
	}

	// Scrape prerequisites
	courseDetail.Prerequisite = stringPtr(strings.TrimSpace(doc.Find("#lblPreequisite").Text()))

	// Add timestamps (automatically generated by GORM when saving)
	courseDetail.CreatedAt = time.Now()
	courseDetail.UpdatedAt = time.Now()

	return &courseDetail, nil
}

func (s *courseDetailService) GetAll() ([]model.SysCourseDetail, error) {
	return s.courseDetailRepo.GetAll()
}

func (s *courseDetailService) GetByCourseNo(courseNo string) (*model.SysCourseDetail, error) {
	return scrapeCourseDetail(courseNo)
}

func (s *courseDetailService) Create(courseDetail model.SysCourseDetail) error {
	return s.courseDetailRepo.Create(&courseDetail)
}

func (s *courseDetailService) Update(courseDetail model.SysCourseDetail) error {
	return s.courseDetailRepo.Update(&courseDetail)
}

func (s *courseDetailService) Delete(courseNo string) error {
	return s.courseDetailRepo.Delete(courseNo)
}
